### ISSUE TITLE
Respect `prideQuiltsEnabled` even when `darkMojangStudiosBackground` is true.

### ISSUE THREAD

**Issue by sleepingdragoninn** [darkerbit/quilt-loading-screen#12]
We'd like to be able to turn on a black background with a bunch of pride quilts, but can't right now.

**Comment by triphora** [comment]
I've largely withdrawn from making mods since I have rather limited free time between work and school. If you (or someone you know) would like to make a PR, I'm happy to merge and release it.

**Comment by sleepingdragoninn** [comment]
Well the double good news is that i was totally ready to do that bugfix but that it totally doesn't exist actually - our config was just resetting between versions unexpectedly - oops! will follow up if the config issue is an actual problem at all, but I doubt it.
