### ISSUE TITLE
No Mod Config option

### ISSUE THREAD

**Issue by mistakeL** [darkerbit/quilt-loading-screen#13]
I don't know what went wrong on my end, but there is no Mod Config, which means I can't make it Pride Month forever :(

![image](https://github.com/triphora/quilt_loading_screen/assets/103278951/41cf4d7a-a2ff-4393-9e64-3926f92669c8)

**Comment by hibiii** [comment]
Hi,

The configuration is accessible through Minecraft's GUI. MidnightLib, the config library that QLS uses, should add a button to the vanilla options screen, to the right of the "Online" button. You can access QLS's config through this screen.

If the button for mods configured through MidnightLib isn't there, you will need to enable it through its own configuration via Mod Menu. If it's not displayed, you'll have to make Mod Menu show libraries.

Hope this helps, let me know if you have any problems.
